Application Framework API Reference: call-command-handler.c File Reference
Home | Modules | Data Structures | File List | Directories | Index
call-command-handler.c File Reference
#include <PLATFORM_HEADER>
#include "stack/include/ember.h"
#include "app/framework/util/util.h"
#include "af-structs.h"
#include "call-command-handler.h"
#include "command-id.h"
#include "callback.h"
Functions
EmberAfStatus emberAfClusterSpecificCommandParse (EmberAfClusterCommand *cmd)
Function Documentation
EmberAfStatus emberAfClusterSpecificCommandParse (EmberAfClusterCommand * cmd)
Definition at line 37 of file call-command-handler.c.
References EmberAfClusterCommand::apsFrame, EmberAfClusterCommand::direction, EMBER_ZCL_STATUS_UNSUP_CLUSTER_COMMAND, emberAfAlarmClusterClientCommandParse(), emberAfAlarmClusterServerCommandParse(), emberAfBacnetProtocolTunnelClusterServerCommandParse(), emberAfBasicClusterServerCommandParse(), emberAfColorControlClusterServerCommandParse(), emberAfCommissioningClusterClientCommandParse(), emberAfCommissioningClusterServerCommandParse(), emberAfDemandResponseLoadControlClusterClientCommandParse(), emberAfDemandResponseLoadControlClusterServerCommandParse(), emberAfDoorLockClusterClientCommandParse(), emberAfDoorLockClusterServerCommandParse(), emberAfGenericTunnelClusterClientCommandParse(), emberAfGenericTunnelClusterServerCommandParse(), emberAfGroupsClusterClientCommandParse(), emberAfGroupsClusterServerCommandParse(), emberAfIasAceClusterClientCommandParse(), emberAfIasAceClusterServerCommandParse(), emberAfIasWdClusterServerCommandParse(), emberAfIasZoneClusterClientCommandParse(), emberAfIasZoneClusterServerCommandParse(), emberAfIdentifyClusterClientCommandParse(), emberAfIdentifyClusterServerCommandParse(), emberAfLevelControlClusterServerCommandParse(), emberAfMessagingClusterClientCommandParse(), emberAfMessagingClusterServerCommandParse(), emberAfOnOffClusterServerCommandParse(), emberAfPrepaymentClusterClientCommandParse(), emberAfPrepaymentClusterServerCommandParse(), emberAfPriceClusterClientCommandParse(), emberAfPriceClusterServerCommandParse(), emberAfRssiLocationClusterClientCommandParse(), emberAfRssiLocationClusterServerCommandParse(), emberAfScenesClusterClientCommandParse(), emberAfScenesClusterServerCommandParse(), emberAfSimpleMeteringClusterClientCommandParse(), emberAfSimpleMeteringClusterServerCommandParse(), emberAfThermostatClusterServerCommandParse(), emberAfTunnelingClusterClientCommandParse(), emberAfTunnelingClusterServerCommandParse(), emberAfWindowCoveringClusterServerCommandParse(), ZCL_ALARM_CLUSTER_ID, ZCL_BACNET_PROTOCOL_TUNNEL_CLUSTER_ID, ZCL_BASIC_CLUSTER_ID, ZCL_COLOR_CONTROL_CLUSTER_ID, ZCL_COMMISSIONING_CLUSTER_ID, ZCL_DEMAND_RESPONSE_LOAD_CONTROL_CLUSTER_ID, ZCL_DOOR_LOCK_CLUSTER_ID, ZCL_GENERIC_TUNNEL_CLUSTER_ID, ZCL_GROUPS_CLUSTER_ID, ZCL_IAS_ACE_CLUSTER_ID, ZCL_IAS_WD_CLUSTER_ID, ZCL_IAS_ZONE_CLUSTER_ID, ZCL_IDENTIFY_CLUSTER_ID, ZCL_LEVEL_CONTROL_CLUSTER_ID, ZCL_MESSAGING_CLUSTER_ID, ZCL_ON_OFF_CLUSTER_ID, ZCL_PREPAYMENT_CLUSTER_ID, ZCL_PRICE_CLUSTER_ID, ZCL_RSSI_LOCATION_CLUSTER_ID, ZCL_SCENES_CLUSTER_ID, ZCL_SIMPLE_METERING_CLUSTER_ID, ZCL_THERMOSTAT_CLUSTER_ID, ZCL_TUNNELING_CLUSTER_ID, and ZCL_WINDOW_COVERING_CLUSTER_ID.
Application Framework API Reference.
Application Framework V2.
Copyright © 2006-2010 by Ember Corporation. All rights reserved.
Generated Tue Oct 12 10:24:38 2010 with Doxygen 1.5.8.