Application Framework API Reference: core-cli.c File Reference
Home | Modules | Data Structures | File List | Directories | Index
core-cli.c File Reference
#include "app/framework/util/common.h"
#include "app/framework/util/af-main.h"
#include "app/util/serial/command-interpreter2.h"
#include "stack/include/library.h"
#include "app/framework/security/af-security.h"
#include "stack/include/cbke-crypto-engine.h"
Defines
#define EMBER_AF_DOXYGEN_CLI__DEBUG_PRINT_COMMANDS
Functions
void emAfCliCountersCommand (void)
void emAfCliResetCommand (void)
void emAfCliHelpCommand (void)
void emAfCliInfoCommand (void)
void emAfCliEchoCommand (void)
Variables
EmberCommandEntry debugPrintCommands []
Function Documentation
void emAfCliCountersCommand (void)
Definition at line 83 of file core-cli.c.
References emberAfAppFlush, and emberAfAppPrintln.
void emAfCliResetCommand (void)
Definition at line 121 of file core-cli.c.
void emAfCliHelpCommand (void)
Definition at line 126 of file core-cli.c.
References emberAfAppFlush, and emberAfAppPrintln.
void emAfCliInfoCommand (void)
Definition at line 212 of file core-cli.c.
References EmberAfEndpointType::cluster, EmberAfEndpointType::clusterCount, EmberAfCluster::clusterId, emberAfAppFlush, emberAfAppPrint, emberAfAppPrintln, emberAfDeviceIdFromIndex, emberAfDeviceVersionFromIndex, emberAfEndpointCount(), emberAfEndpointFromIndex, emberAfGetEui64(), emberAfIsDeviceEnabled(), emberAfPrintBigEndianEui64(), emberAfProfileIdFromIndex, endpoints, and EmberAfDefinedEndpoint::endpointType.
void emAfCliEchoCommand (void)
Definition at line 290 of file core-cli.c.
Variable Documentation
EmberCommandEntry debugPrintCommands[]
Definition at line 65 of file core-cli.c.
Application Framework API Reference.
Application Framework V2.
Copyright © 2006-2010 by Ember Corporation. All rights reserved.
Generated Tue Oct 12 10:24:38 2010 with Doxygen 1.5.8.