Application Framework API Reference: security-cli.c File Reference
Home | Modules | Data Structures | File List | Directories | Index
security-cli.c File Reference
#include "app/framework/util/common.h"
#include "app/framework/util/service-discovery.h"
#include "app/framework/cluster/key-establishment.h"
#include "app/framework/cluster/key-establishment-partner.h"
#include "app/util/serial/command-interpreter2.h"
#include "app/framework/cli/security-cli.h"
#include "app/framework/security/security-config.h"
#include "app/framework/util/af-main.h"
#include "app/framework/security/af-security.h"
Defines
#define EMBER_AF_DOXYGEN_CLI__SECURITY_CHANGEKEY_COMMANDS
#define EMBER_AF_DOXYGEN_CLI__SECURITY_CBKE_COMMANDS
Functions
void changeKeyCommand (void)
void keyUpdateCommand (void)
void printTextLine (PGM_P text)
void printIeeeLine (const EmberEUI64 ieee)
void printKeyInfo (void)
void printCert (const int8u *cert)
void printZigbeeKey (const int8u *key)
void printKey (boolean publicKey, const int8u *key)
void printSignature (int8u *sig)
void print8ByteBlocks (int8u numBlocks, const int8u *block, boolean crBetweenBlocks)
void printIssuer (const int8u *issuer)
Variables
EmberKeyData cliPreconfiguredLinkKey
EmberKeyData cliNetworkKey
EmberCommandEntry changeKeyCommands []
Function Documentation
void changeKeyCommand (void)
Definition at line 109 of file security-cli.c.
References cliNetworkKey, cliPreconfiguredLinkKey, emberAfCorePrintln, and emberAfDebugPrintln.
void keyUpdateCommand (void)
Definition at line 122 of file security-cli.c.
References emberAfCorePrintln.
void printTextLine (PGM_P text)
Definition at line 205 of file security-cli.c.
References emberAfCorePrintln.
void printIeeeLine (const EmberEUI64 ieee)
Definition at line 210 of file security-cli.c.
References emberAfPrintBigEndianEui64().
void printKeyInfo (void)
Definition at line 215 of file security-cli.c.
References emberAfCoreFlush, emberAfCorePrint, emberAfCorePrintln, and printZigbeeKey().
void printCert (const int8u * cert)
Definition at line 253 of file security-cli.c.
References print8ByteBlocks().
void printZigbeeKey (const int8u * key)
Definition at line 259 of file security-cli.c.
References print8ByteBlocks().
Referenced by printKey(), and printKeyInfo().
void printKey (boolean publicKey, const int8u * key)
Definition at line 267 of file security-cli.c.
References emberAfCoreFlush, emberAfCorePrintBuffer, emberAfCorePrintln, and printZigbeeKey().
void printSignature (int8u * sig)
Definition at line 279 of file security-cli.c.
References print8ByteBlocks().
void print8ByteBlocks (int8u numBlocks, const int8u * block, boolean crBetweenBlocks)
Definition at line 284 of file security-cli.c.
References emberAfCoreFlush, emberAfCorePrint, and emberAfCorePrintBuffer.
Referenced by printCert(), printIssuer(), printSignature(), and printZigbeeKey().
void printIssuer (const int8u * issuer)
Definition at line 305 of file security-cli.c.
References emberAfCorePrint, and print8ByteBlocks().
Variable Documentation
EmberKeyData cliPreconfiguredLinkKey
Definition at line 31 of file security-cli.c.
Referenced by changeKeyCommand().
EmberKeyData cliNetworkKey
Definition at line 32 of file security-cli.c.
Referenced by changeKeyCommand().
EmberCommandEntry changeKeyCommands[]
Definition at line 80 of file security-cli.c.
Application Framework API Reference.
Application Framework V2.
Copyright © 2006-2010 by Ember Corporation. All rights reserved.
Generated Tue Oct 12 10:24:38 2010 with Doxygen 1.5.8.