Application Framework API Reference: zcl-cli.c File Reference
Home | Modules | Data Structures | File List | Directories | Index
zcl-cli.c File Reference
#include "app/framework/util/common.h"
#include "app/framework/util/af-main.h"
#include "app/framework/util/attribute-storage.h"
#include "app/framework/util/service-discovery.h"
#include "app/util/serial/command-interpreter2.h"
#include "app/framework/cli/security-cli.h"
#include "app/framework/cli/zcl-cli.h"
#include "app/framework/cli/ota-cli.h"
#include "app/framework/cluster/key-establishment.h"
#include "app/framework/cluster/key-establishment-partner.h"
#include "app/framework/report/report-table.h"
#include "app/util/concentrator/concentrator.h"
#include "app/util/common/library.h"
Defines
#define APP_ZCL_BUFFER_SIZE
#define APP_ZCL_BUFFER_SIZE_CLI
#define EMBER_AF_DOXYGEN_CLI__ZCL_GLOBAL_COMMANDS
#define zclSimpleClientCommand(clusterId, commandId)
#define zclSimpleServerCommand(clusterId, commandId)
#define MAX_ATTR_DATA_SIZE
Functions
void emAfCliRawCommand (void)
void makeZclBuffer (int8u frameControl, int16u clusterId, int8u commandId, char *format,...)
void emAfCliAddReportEntryCommand (void)
int8u getEndpointArgument (int8u index)
void emAfCliSendCommand (void)
void emAfCliBsendCommand (void)
void emAfCliTimesyncCommand (void)
void emAfCliReadCommand (void)
void emAfCliWriteCommand (void)
void eraseKeyTableEntry (int8u index)
Variables
int8u appZclBuffer [APP_ZCL_BUFFER_SIZE]
int16u appZclBufferLen
boolean zclCmdIsBuilt
EmberApsFrame globalApsFrame
boolean emAfSyncingTime
EmberCommandEntry zclGlobalCommands []
EmberCommandEntry zclTestResponseCommands []
EmberCommandEntry zclTestCommands []
EmberCommandEntry zclMessageCommands []
EmberCommandEntry zclCommands []
EmberCommandEntry interpanCommands []
EmberCommandEntry printCommands []
EmberCommandEntry optionPrintRxCommands []
EmberCommandEntry optionBindingCommands []
EmberCommandEntry optionApsSecurityCommands []
EmberCommandEntry apsretryCommands []
EmberCommandEntry optionSecurityCommands []
EmberCommandEntry optionCommands []
boolean emberAfPrintReceivedMessages
boolean afApsSecurityOff
int8u emberAfApsRetryOverride
EmberCommandEntry keysCommands []
Define Documentation
#define APP_ZCL_BUFFER_SIZE
Definition at line 96 of file zcl-cli.c.
#define APP_ZCL_BUFFER_SIZE_CLI
Definition at line 100 of file zcl-cli.c.
Referenced by emAfCliRawCommand().
#define zclSimpleClientCommand (clusterId, commandId)
Definition at line 1008 of file zcl-cli.c.
#define zclSimpleServerCommand (clusterId, commandId)
Definition at line 1013 of file zcl-cli.c.
#define MAX_ATTR_DATA_SIZE
Definition at line 2683 of file zcl-cli.c.
Referenced by emAfCliReadCommand(), and emAfCliWriteCommand().
Function Documentation
void emAfCliRawCommand (void)
Definition at line 850 of file zcl-cli.c.
References APP_ZCL_BUFFER_SIZE_CLI, appZclBuffer, appZclBufferLen, emberAfNextSequence(), and ZCL_MANUFACTURER_SPECIFIC_MASK.
void makeZclBuffer (int8u frameControl, int16u clusterId, int8u commandId, char * format, ...)
Definition at line 935 of file zcl-cli.c.
References appZclBuffer, and appZclBufferLen.
void emAfCliAddReportEntryCommand (void)
Definition at line 1141 of file zcl-cli.c.
References CLUSTER_MASK_CLIENT, CLUSTER_MASK_SERVER, EMBER_AF_DATA_TYPE_ANALOG, EMBER_ZCL_STATUS_SUCCESS, emberAfGetAttributeAnalogOrDiscreteType(), emberAfGetDataSize(), and emberAfReportingPrintln.
int8u getEndpointArgument (int8u index)
Definition at line 1743 of file zcl-cli.c.
References emberAfEndpointFromIndex.
void emAfCliSendCommand (void)
Definition at line 2352 of file zcl-cli.c.
References appZclBuffer, appZclBufferLen, emberAfCorePrintln, emberAfDebugFlush, emberAfDebugPrint, emberAfDebugPrintBuffer, emberAfDebugPrintln, emberAfGetCurrentTime(), emberAfResponseWaitingFlag, emberAfSendBroadcast(), emberAfSendMulticast(), emberAfSendUnicast(), globalApsFrame, and zclCmdIsBuilt.
Referenced by emAfCliTimesyncCommand().
void emAfCliBsendCommand (void)
Definition at line 2431 of file zcl-cli.c.
References appZclBuffer, appZclBufferLen, emberAfCorePrintln, emberAfGetCurrentTime(), emberAfSendUnicast(), globalApsFrame, and zclCmdIsBuilt.
void emAfCliTimesyncCommand (void)
Definition at line 2500 of file zcl-cli.c.
References emAfCliSendCommand(), emAfSyncingTime, ZCL_FRAME_CONTROL_CLIENT_TO_SERVER, ZCL_PROFILE_WIDE_COMMAND, ZCL_READ_ATTRIBUTES_COMMAND_ID, ZCL_TIME_ATTRIBUTE_ID, ZCL_TIME_CLUSTER_ID, and zclCmdIsBuilt.
void emAfCliReadCommand (void)
Definition at line 2686 of file zcl-cli.c.
References CLUSTER_MASK_CLIENT, CLUSTER_MASK_SERVER, EMBER_ZCL_STATUS_SUCCESS, emberAfCorePrint, emberAfCorePrintBuffer, emberAfCorePrintln, emberAfCorePrintString, emberAfGetDataSize(), emberAfIsThisDataTypeAStringType(), emberAfReadAttribute(), and MAX_ATTR_DATA_SIZE.
void emAfCliWriteCommand (void)
Definition at line 2727 of file zcl-cli.c.
References CLUSTER_MASK_CLIENT, CLUSTER_MASK_SERVER, emberAfCorePrint, emberAfCorePrintln, emberAfGetDataSize(), emberAfIsThisDataTypeAStringType(), emberAfWriteAttribute(), and MAX_ATTR_DATA_SIZE.
void eraseKeyTableEntry (int8u index)
Definition at line 3080 of file zcl-cli.c.
References emberAfCorePrintln.
Variable Documentation
int8u appZclBuffer[APP_ZCL_BUFFER_SIZE]
Definition at line 105 of file zcl-cli.c.
Referenced by emAfCliBsendCommand(), emAfCliRawCommand(), emAfCliSendCommand(), and makeZclBuffer().
int16u appZclBufferLen
Definition at line 106 of file zcl-cli.c.
Referenced by emAfCliBsendCommand(), emAfCliRawCommand(), emAfCliSendCommand(), and makeZclBuffer().
boolean zclCmdIsBuilt
Definition at line 107 of file zcl-cli.c.
Referenced by emAfCliBsendCommand(), emAfCliSendCommand(), and emAfCliTimesyncCommand().
EmberApsFrame globalApsFrame
Definition at line 108 of file zcl-cli.c.
Referenced by emAfCliBsendCommand(), and emAfCliSendCommand().
boolean emAfSyncingTime
Definition at line 119 of file zcl-cli.c.
Referenced by emAfCliTimesyncCommand().
EmberCommandEntry zclGlobalCommands[]
Definition at line 350 of file zcl-cli.c.
EmberCommandEntry zclTestResponseCommands[]
Definition at line 365 of file zcl-cli.c.
EmberCommandEntry zclTestCommands[]
Definition at line 371 of file zcl-cli.c.
EmberCommandEntry zclMessageCommands[]
Definition at line 638 of file zcl-cli.c.
EmberCommandEntry zclCommands[]
Definition at line 706 of file zcl-cli.c.
EmberCommandEntry interpanCommands[]
Definition at line 2547 of file zcl-cli.c.
EmberCommandEntry printCommands[]
Definition at line 2615 of file zcl-cli.c.
EmberCommandEntry optionPrintRxCommands[]
Definition at line 2794 of file zcl-cli.c.
EmberCommandEntry optionBindingCommands[]
Definition at line 2803 of file zcl-cli.c.
EmberCommandEntry optionApsSecurityCommands[]
Definition at line 2811 of file zcl-cli.c.
EmberCommandEntry apsretryCommands[]
Definition at line 2817 of file zcl-cli.c.
EmberCommandEntry optionSecurityCommands[]
Definition at line 2824 of file zcl-cli.c.
EmberCommandEntry optionCommands[]
Definition at line 2829 of file zcl-cli.c.
boolean emberAfPrintReceivedMessages
boolean afApsSecurityOff
int8u emberAfApsRetryOverride
EmberCommandEntry keysCommands[]
Definition at line 3055 of file zcl-cli.c.
Application Framework API Reference.
Application Framework V2.
Copyright © 2006-2010 by Ember Corporation. All rights reserved.
Generated Tue Oct 12 10:24:38 2010 with Doxygen 1.5.8.